In [68]:
# generate random data and apply filters
import pandas as pd
import random
products=[]
for i in range(5):
    id=random.randint(1,10)
    pricing={"laptop":5000,"mobile":10000,"tv":12000,"induction":20000,"AC":65000}
    name=random.choice(["laptop","mobile","tv","induction","AC"])
    price=pricing[name]
    product={
        "productid":id,
        "productname":name,
        "price":price
    }
    products.append(product)

df=pd.DataFrame(products)
df.set_index("productid")
df[(df["productid"]%2==0) & (df["price"]>500)]

   productid productname  price
0          8   induction  20000
2          2      laptop   5000
3          4   induction  20000

In [ ]:
# 1.import pandas and random Module
# 2.create a empty list of products
# 3.take a range 5 for 5 inputs
# 4.generate random id,name,price
# 5.append that data in a products list
# 6.convert into dataframe then apply filters

In [ ]:
# input from user side
import pandas as pd

product=[]
for i in range(5):
    id=int(input("enter id"))
    name=input("enter product")
    price=int(input("price"))
    product.append({"productid":id,"productname":name,"price":price})
products=pd.DataFrame(product)

In [7]:
products

  productid productname  price
0         1          tv  12000
1         2      laptop   5000
2         3      remote    200
3         4   induction  19000
4         5      mobile  10000

In [24]:
a=products["productid"].to_numpy(dtype=int)
b=products["price"].to_numpy(dtype=int)

In [25]:
print(a.dtype)

int64

In [35]:
products[(a % 2 == 0) & (b > 50)]

  productid productname  price
1         2      laptop   5000
3         4   induction  19000

In [ ]:
# 1.import pandas
# 2.create product list
# 3.take the input from users
# 4.append inputs in a list
# 5.convert list into dataframe
# 6.apply filters on that

In [99]:
a=[10,20,34,56,76]
b=[]
for i in range(5):
   b.append(random.choice(a))
print(b)

[10, 10, 34, 56, 20]